### ISSUE TITLE
future research

### ISSUE THREAD

**Issue by jawz101** [jawz101/MobileAdTrackers#1]
- find a collection of analyzed APK's for "interesting strings" (aka url's /domain names discovered within the code.)  VirusTotal has this sort of information but it doesn't appear to have the filtering capabilities to get it.
- sift through the domains and figure out the ad/analytic companies
- run those domains through something like [Anubis ](https://github.com/jonluca/Anubis)- subdomain enumeration tool to gather their associated domains
- apply those to the list
- run list through a domain validation tool (ping, whois, etc.) to make sure they still exist.

**Comment by jawz101** [comment]
https://exodus-privacy.eu.org/

**Comment by Atavic** [comment]
[Repo](https://github.com/Exodus-Privacy/exodus) & [issue](https://github.com/Exodus-Privacy/exodus/issues/40).

**Comment by Atavic** [comment]
On the ref. issue you asked:

>I don't know if the network signature are what DNS record strings are contained within an app or if its based on what domains are seen in a live test of an app

It seems the latter.

'Exodus is meant to find *trackers signature* in unzipped APK *and* analyze the *network traffic* generated by the application' (stripped cit.) so the list of Code signatures and Java classes in the ref. issue pertain to the first step only. The second step is to find the means of tracking used by these companies:

- By blocking the AS of a company (ASN-blocking)
- By listing the domains used (DNS66)
- By listing the IPs owned by every single company
- By listing the js scripts used (Decentraleyes, uMatrix)

**Comment by Atavic** [comment]
A good example of what can be done is [this post](https://github.com/crazy-max/WindowsSpyBlocker/issues/93#issuecomment-370204892) and repo.

**Comment by jawz101** [comment]
More subdomain enumeration tools:

https://github.com/aboul3la/Sublist3r
https://github.com/darryllane/Bluto
https://github.com/jonluca/Anubis
https://github.com/michenriksen/aquatone
https://github.com/fwaeytens/dnsenum
http://mor-pah.net/software/dmitry-deepmagic-information-gathering-tool/
https://github.com/jevalenciap/iptodomain
https://github.com/caffix/amass
