### ISSUE TITLE
False Positive: cdn.parcel2go.com

### ISSUE THREAD

**Issue by greggchappell** [jawz101/MobileAdTrackers#14]
Hello,

The domain we use to host static content on our site has made it onto this list. Please could it be removed?

Thanks

**Comment by jawz101** [comment]
removed.  And congratulations for being on the top 1million most requested DNS records according to OpenDNS :)  Sorry about that.  My recent bulk upload has been a little misguided but now I'm going through and trying to clean it up.

Thank you for the feedback!
