### ISSUE TITLE
AdGuard: a few clarifications

### ISSUE THREAD

**Issue by ameshkov** [jawz101/MobileAdTrackers#18]
Hi!

I just wanted to clarify some things from the article:
https://github.com/jawz101/MobileAdTrackers/wiki/Android-adblockers-compared

> The advantages NetGuard has over AdGuard that it's all open source and that it lets you block individual domains per-app.

By default, when you do this from the filtering log, AdGuard blocks domains per-app:
* https://uploads.adguard.com/up04_63co8_2019-05-20_19.34.22.jpg.png
* https://uploads.adguard.com/up04_9pcoo_2019-05-20_19.34.29.jpg.png

> For one, even on the list of sites they include, they do not account for subdomains of those domains

This is not true - it includes subdomains, and it's easy to check.

> Also, I would feel slightly more secure if the cert was completely unique every time I generated it.

It is completely unique every time it is generated. Once it's generated (right on your device), it is stored in the app settings, and in order to re-generate it, you can simply clear the app data.

> There is no reason it should always apply the same cert for every device for every user. If it isn't intentionally fishy, it just doesn't seem right.

This would be a serious security issue, and that's why it does not work that way.

> Even when you create the cert it says it doesn't work on Android Nougat or higher.

It does not say that. HTTPS filtering is limited to browsers on Android 7+, though. On the other hand, this feature is most important for cosmetic rules which are used in browsers only.

> And what about your password manager's traffic

Your password manager is an app so it's HTTPS traffic is not filtered. Also, the default exclusions list is not limited to banks, LastPass and 1Password domains are listed there as well. 

You are right that this whole topic is a matter of trust, though.

**Comment by jawz101** [comment]
Thank you for the clarifications.  I'll edit that wiki page.

But even so, what would the point be to do SSL interception if it's only for browser pages?  How often is it encountered that you would have content within the web traffic that needed to be carved out?  Is it because it's an app trying to hook into a browser's traffic whereas a browser add-on would not need to intercept in the same manner?

**Comment by ameshkov** [comment]
> How often is it encountered that you would have content within the web traffic that needed to be carved out?

All the time actually, and it's not just about carving out.

Just some things that came to my mind:
1. Cosmetic rules cannot be applied without it at all;
2. Stealth mode cannot work without it (changing user agent, referrer, removing cookies, etc);
3. AG removes HTML elements that point to blocked URLs right from the page code which is better as the browser does not attempt to load anything;
4. Userscripts support we're planning to add in v3.2 also requires https filtering;

> Is it because it's an app trying to hook into a browser's traffic whereas a browser add-on would not need to intercept in the same manner?

Yep, browser extensions are injected into every page and can observe them and their web requests from inside the browser. Same as with https filtering, you need to trust the extension developer because extensions have access to everything that you see or do on the internet. On the other hand, it's relatively easy to inspect what extension does unless the code is heavily minimized or obfuscated.

> It's still a very limited set of financial institutions, no whitelist for .gov sites. If I go to irs.gov or any one of the hundreds of thousands of governments sites around the world... it's just too much to try to whitelist.

I can't argue here. The list is crowdsourced and we accept requests, but still, there are a lot of domains that should be added there.

> I still think the https filtering is not a good idea. Nothing would be missed if it wasn't a feature.

Well, there are a lot of people who would disagree. Take AdGuard Home, for instance: proxy with HTTPS filtering support was one of the very first feature requests made after AGH was revealed. In the case of AG for Android, it was by far the most popular feature request back in the days.

On the other hand, you are not alone. Some renown devs argue that there's no place for a middleware between the client and the server. Anyway, this is a topic for a longer discussion, sorry for bothering you with the explanation that long.

**Comment by jawz101** [comment]
Thank you.  I appreciate your insights.  Possibly someday you all could write a blog post explaining why https filtering is needed when the ad blocking implementation is done via an external app as opposed to a browser add-on.
