### ISSUE TITLE
api.luftdaten.info

### ISSUE THREAD

**Issue by ricki-z** [jawz101/MobileAdTrackers#19]
Hello,
please remove this host from your blocking list. This host is used by some apps to get air quality data and NOT to load ads.
You can't use DNS requests only to get ad server. I won't imagine how many false positives are in this list. There may be many apps accessinf different hosts to load data needed to work with the app.
And as your list is used by https://github.com/EnergizedProtection , which seems to be used by many pi-hole users, these users can't access hosts listed here.

**Comment by jawz101** [comment]
I cannot find it in this list.  Energized Protection hasn't been updated in over a month and I'm not responsible for that list.

**Comment by millermoneytime** [comment]
Who is jawz101

**Comment by jawz101** [comment]
What?
