### ISSUE TITLE
Whitelist required for crunchyroll app to work

### ISSUE THREAD

**Issue by Thomas499** [jawz101/MobileAdTrackers#20]
api.crunchyroll.com

If you download the crunchyroll app on firestick and try to open it with this list enabled : https://raw.githubusercontent.com/jawz101/MobileAdTrackers/master/hosts

you will see this when you try to open the app
![image](https://user-images.githubusercontent.com/38442058/58978637-1850f300-8781-11e9-8c44-d777cb070489.png)

if you whitelist **api.crunchyroll.com** and re-open the app you will see this (which is how it should be)

![image](https://user-images.githubusercontent.com/38442058/58978690-36b6ee80-8781-11e9-9912-f6114b8ddc3a.png)

**Comment by jawz101** [comment]
Thanks!  Removed.
