### ISSUE TITLE
Hey @jawz101

### ISSUE THREAD

**Issue by spirillen** [jawz101/MobileAdTrackers#29]
Hi @jawz101 I sent you a text on keybase, but I'm not sure you are there, so here is a copy

> Hey jawz I was wondering if you would like to make an exchange of my hosts formatted files, and then you get me your's records that can be wild carded in DNS? (https://gitlab.com/my-privacy-dns/matrix/matrix)
> 
> From what I can see we are about equally strict on what to block and what not.

**Comment by jawz101** [comment]
I don't know what keybase is.  And I'm not sure what you're asking.

**Comment by spirillen** [comment]
`keybase.io` is a "chat" program that serves end to end encryption.

The second and most important part is that I hold a couple of hosts formatted files, which I'm not that keen to maintain, as I do my stuff in DNS by [RPZ](http://wiki.mypdns.org/wiki/RPZ) which endorse to wildcard ex: `swrve.com` (http://wiki.mypdns.org/ticket/110) where 410 of your records becomes 2 records ([1 in repo file](http://wiki.mypdns.org/browser/Matrix/source/tracking/wildcard.list?rev=dc16c2c&marks=428#L425) :smiley: )

So My idea is, you maintain the hosts formatted files, I report to you, and I get any domains that could/should be wild-carded from you, This way we both got a win-win by co-operate with each other to maintain the project.

We have the goal, but achieving it in two different ways.

**Comment by jawz101** [comment]
I don't think I'd want to maintain another list at this time.  You can certain take anything from my list or now the Adaway one since I am focusing on it now.

**Comment by spirillen** [comment]
U2 :smiley:
