### ISSUE TITLE
imapi-mu.isnssdk.com

### ISSUE THREAD

**Issue by p1r473** [jawz101/MobileAdTrackers#32]
This domain breaks Direct Messages in the Social Media app "TikTok"

**Comment by jawz101** [comment]
updated w/ latest Adaway list.  I really don't maintain this list except to pull in the latest changes from Adaway every now and then as I now maintain the Adaway list.

**Comment by p1r473** [comment]
Are you going to delete this list if you are now only doing AdAway list?

**Comment by jawz101** [comment]
I don't know if I can because it's still a default list in Blokada

**Comment by p1r473** [comment]
Ok, in that case, please don't mind if I report false positivds.

**Comment by spirillen** [comment]
Hey @jawz101 according to https://github.com/jawz101/MobileAdTrackers/issues/32#issuecomment-634986640 why don't you setup a travis-ci job to publish the adaway list to this repo? then everytime you push something on AdAway it is also published here?

All it requires is a simple bash script than do the ordinary git commands - or a bit more advanced checking for success vs failures of pushing

**Comment by jawz101** [comment]
the other option is I just delete this repo.  I'm not really interested in doing anything differently than what I am currently doing.  The other reason I keep it is to track down why things ended up on either list since the orignal commit history is in the MATS repo.

**Comment by spirillen** [comment]
@jawz101 I do follow you, my idea was just based in the part of your comment

> Every month or so I just copy over the latest Adaway list... changing the formatting a little

But keeping the history is a very well funded reason to keep it, but there is a archive function you could activate, and if I remembers it right you can post a link to AdAway there.

It's up to you, it was purely a couple of suggestions :sun_with_face:
