### ISSUE TITLE
Some hosts that are candidates for whitelisting

### ISSUE THREAD

**Issue by notracking** [jawz101/MobileAdTrackers#4]
Hi There!

I've found some entries in your list that match my own whitelists. I've whitelisted these hosts because they will otherwise break actual useful functions of apps or websites (or are simply just legit sites).

You can find my complete list [here](https://github.com/notracking/hosts-blocklists-scripts/blob/master/hostnames.whitelist.txt) (in case it might be of any help to you).

```
0.0.0.0 api.uca.cloud.unity3d.com
0.0.0.0 s3.amazonaws.com
0.0.0.0 analytics.google.com
0.0.0.0 s3.amazonaws.com
0.0.0.0 api.ipify.org
0.0.0.0 googleadapis.l.google.com
0.0.0.0 yandex.ru
0.0.0.0 s0.2mdn.net
0.0.0.0 redirector.gvt1.com
0.0.0.0 sentry.io
0.0.0.0 mingle.kijiji.ca
0.0.0.0 redirector.gvt1.com
0.0.0.0 unity3d.com
0.0.0.0 s0.wp.com
0.0.0.0 redirector.googlevideo.com
0.0.0.0 vjs.zencdn.net
0.0.0.0 scontent.xx.fbcdn.net
0.0.0.0 cdn.auth0.com
0.0.0.0 cloud.typography.com
0.0.0.0 api.fast.com
0.0.0.0 cdn.gigya.com
0.0.0.0 maxcdn.bootstrapcdn.com
```

**Comment by jawz101** [comment]
edit: I took a few more off.  Still didn't see much compelling reason for some of the others yet.

fonts usually get through with `maxcdn.bootstrapcdn.com, cloud.typography.com`

Personally, I'm not a big typography fan unless it cripples a relatively important web page.

At the expense of potentially tracking every visitor to a site, I don't know why users should choose to have a font delivery network track them.  And the other reason I don't like them is when I block 3rd party scripts and frames, I'll see these 300KB+ woff files still get through.  Fonts alone just don't feel right to take 30% of the remaining unblocked traffic on a web page- especially on a mobile device.

`cdn.gigya.com` gigya is some identity management product.  I have yet to see it be used for desired identity mgmt.

`scontent.xx.fbcdn.net` I've not seen this cause breakage on facebook apps, sites, or apps that use FB login.  I've seen some domains end with that but not it directly except when playing around with an solitaire game by microsoft that had Facebook ads. Blocking that specific subdomain seemed to do the trick.

`vjs.zencdn.net` I haven't browsed anywhere where this blocked anything crucial yet but that may change

`redirector.googlevideo.com` searching around, it looks like this is used to link to videos hosted on Google Drive.  In the examples I've seen so far, it's some janky site that it's using Google Drive as a poor man's media delivery network.  Or maybe a crappy video ad network.  Regardless, unless people say it's used by Google themselves, Google Drive app sharing vids things amongst friends, or by legit businesses who use GSuite products, I probably won't remove it until then.

**Comment by notracking** [comment]
The link to my whitelist holds some more info regarding some of these, most of them refer to a ticket submitted by one of my users. I have to admit that I'm not always writing down the info from my investigations, but it might help you. I will try to write down more details about my findings in the future.

I always take in to account that false calls will cause users to stop or bypassing the blocklists at one point, because it's simply annoying (making the situation even worse). Especially since I maintain lists that are mostly used for network wide filtering. Though we're in the same boat regarding webfonts, I'm still whitelisting the legit cdn that do supply fonts and that are not to obviously used for tracking / ad injection purposes, because you could otherwise also consider blocking all image hosts, since these (in most cases) are also not adding critical info to a lot of apps / websites. But that is my way of looking at it.

Some remarks about the remaining block that I can still remember more about:
```
scontent.xx.fbcdn.net I'm not a FB user, but people reported that this is also used for content delivery of user images / video etc.
analytics.google.com This domain is not used for tracking, but only serves the admin interfaces for the site owners
gigya.com will break the video delivery of some news websites, though when using a system that allows for content manipulation (like uBlock Origin), this one can safely be blocked (not the use-case for most of my users).
```
