### ISSUE TITLE
A couple hosts to consider whitelisting

### ISSUE THREAD

**Issue by lightswitch05** [jawz101/MobileAdTrackers#5]
Hello - thank you for maintaining this list. I have come across a few hosts that might be a little too aggressive and thought I might open this ticket to see if you would reconsider them.

 #### Font Awesome

* `pro.fontawesome.com`
* `use.fontawesome.com`

Font Awesome is more then just a regular font provider - they are an Icon provider. Some buttons/links on websites only use icons to show users the actions. This is useful since icons are not language specific and take up little space.

#### jsDelivr

jsDelivr is a CDN to host any type of content. While it can certainly be used to host ads and trackers - it often is used to host benign content. Here is an example, this link is using jsDelivr as a CDN for this very hosts list: https://cdn.jsdelivr.net/gh/jawz101/MobileAdTrackers@latest/hosts

* `cdn.jsdelivr.net`

#### zencdn.net

* `vjs.zencdn.net (https://vjs.zencdn.net/vttjs/0.12.5/vtt.global.min.js)`

If you load the above javascript, you'll find its form: https://github.com/gkatsev/vtt.js - which is: "Implementation of the WebVTT spec in JavaScript.". This is used for playing videos in the browser. I've found blocking it breaks a lot of news websites.

**Comment by jawz101** [comment]
The bottom 2 were removed yesterday during I scrubbing.  I went ahead and removed the fontawesome ones just now.  Reluctantly :P

**Comment by jawz101** [comment]
... actually, I've reverted that fontawesome removal.  I convinced myself that I don't like them.

**Comment by lightswitch05** [comment]
Thanks for removing them. I've read their privacy policy. I don't care for the CDN's privacy policy (MaxCDN and Fly.io) - but I don't think fontawesome's is particularly bad. 

> Font Awesome usually stores data about how you use content delivery networks in identifiable form for just a few weeks.

**Comment by lightswitch05** [comment]
@jawz101 can you explain in more detail? I have my own hosts list that I'm pretty aggressive on - but I don't see why fontawesome should be there.

**Comment by jawz101** [comment]
It's the Incorporated part that bugs me and that I can't find a website for the corporation so I don't know why they have a business model.  Personally, I haven't seen any significant breakage and also- this list is meant for mobile devices.  When it takes 9% of a page's download size to draw 4 down arrows with javascript, css, and woff files that just seems silly.

![image](https://user-images.githubusercontent.com/14151703/48081031-b4e3f000-e1b4-11e8-8e01-2d549becd2f5.png)

**Comment by lightswitch05** [comment]
[FontAwesome](https://github.com/FortAwesome/Font-Awesome) was created as a free and open source tool by @davegandy. It eventually got so popular that there was a kickstarter for a paid new version with extra features. This **is** the companies website.

It would be great if Mr Gandy or someone else from the FontAwesome team could take a moment and chime in that they are not doing anything shady with the data per their privacy policy (tracking, ads, or targeting). I don't believe they warrant being in this block list.

**Comment by jawz101** [comment]
That's up to you to get him to chime in.  Ultimately, this is for data savings and I'm only concerned with the meat of a web page.  In the end, this is just my list.  It can be forked/copied any time by anyone for any reason they have.  I just wanted a place to host it for family & myself.  If anyone else wants to use it that's fine too.

**Comment by beerisgood** [comment]
How is status for cdn.jsdelivr.net ?

**Comment by jawz101** [comment]
fixed
