### ISSUE TITLE
NYTimes breakage

### ISSUE THREAD

**Issue by KrisNM** [jawz101/MobileAdTrackers#6]
Hi, samizdat.nytimes.com is required for NYTimes android app (com.nytimes.android).

If it blocked, it can't fetch any news, saying "i'm offline".

Regards.

**Comment by jawz101** [comment]
removed.  Thanks!

**Comment by KrisNM** [comment]
Seems it included again.. 

Do you have any reason to do it, or is it just a mistake?

This url is not a tracker or adserver, it's required—at least for its mobile app.. Blocking it would make its app literally go blank (not displaying anything).

**Comment by jawz101** [comment]
fixed.  sorry about that
