### ISSUE TITLE
false positiv: dict.leo.org

### ISSUE THREAD

**Issue by beerisgood** [jawz101/MobileAdTrackers#8]
dict.leo.org is a normal translator site.
Virustotal say it's clean: https://www.virustotal.com/#/url/a28b9e663f4831d7d2e06aeb7c8ea25eea8ead08403958faff2e7f791cdfedad/detection

**Comment by jawz101** [comment]
Will remove right now.  Thanks!  After importing a few lists - AdGuard's and a couple from iOS users I'd found - I've been trying to wrangle the list back in so any input is helpful.

**Comment by beerisgood** [comment]
Fixed
